### ISSUE TITLE
[BUG] Transformations cannot be pickled 

### ISSUE THREAD

**Issue by cedricrupb** [Flo0112358/semtransforms#1]
The current implementation of the transformation do not allow the implementation to be pickled. However, this is important for running multiple transformations in parallel across multiple processes. Using threads is not an option (because of GIL).

Example:
```python
import pickle
from semtransforms.transformations import add_if1

pickle.dumps([add_if1])
```

Error:
```
PicklingError: Can't pickle <function add_if1 at 0x109dc1b40>: it's not the same object as semtransforms.transformations.strong.add_if1
```

**Comment by FlorianDyck** [comment]
multiprocessing.Pool was replaced with pathos.pools.ProcessPool which uses dill instead of pickle which can serialize transformations

**Comment by cedricrupb** [comment]
Thank you. Using pathos instead of the standard library closes this issue.
